"""empty message

Revision ID: 5b9e75ce3a1e
Revises: 967184a8d04e
Create Date: 2026-02-06 18:50:14.086753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9e75ce3a1e'
down_revision: Union[str, Sequence[str], None] = '967184a8d04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('current_stop_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('rides_сurrent_stop_id_fkey'), 'rides', type_='foreignkey')
    op.create_foreign_key(None, 'rides', 'stops', ['current_stop_id'], ['id'])
    op.drop_column('rides', 'сurrent_stop_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('сurrent_stop_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.create_foreign_key(op.f('rides_сurrent_stop_id_fkey'), 'rides', 'stops', ['сurrent_stop_id'], ['id'])
    op.drop_column('rides', 'current_stop_id')
    # ### end Alembic commands ###
